services:
  mysql:
    image: mysql:8.0
    container_name: ltjava-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-LTJava}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}
      TZ: UTC
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
#    healthcheck:
#      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p$$MYSQL_ROOT_PASSWORD --silent"]
#      interval: 5s
#      timeout: 3s
#      retries: 20

  redis:
    image: redis:7-alpine
    container_name: ltjava-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build:
      context: ./LTJava
      dockerfile: Dockerfile
    container_name: ltjava-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker

      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE:-LTJava}
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD:-123456}

      REDIS_HOST: redis
      REDIS_PORT: 6379

      GEMINI_API_KEY: ${GEMINI_API_KEY:-}
    ports:
      - "8082:8081"
    depends_on:
#      mysql:
##        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ltjava-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql_data:
  redis_data:
